spring:
    application:
        name: backend

    config:
        import: optional:configserver:http://140.245.66.84:8888

    cloud:
        config:
            name: travelingdog
            profile: prod
