spring:
    application:
        name: backend

    config:
        import: optional:configserver:http://localhost:8888

    cloud:
        config:
            name: travelingdog
            profile: local

    datasource:
        driver-class-name: org.postgresql.Driver

    jpa:
        hibernate:
            ddl-auto: update
        properties:
            hibernate:
                dialect: org.hibernate.dialect.PostgreSQLDialect
                "[format_sql]": true
