spring:
    application:
        name: backend
    datasource:
        url: jdbc:mysql://localhost:3306/backend
        username: root
        password: 1234
    jpa:
        hibernate:
            ddl-auto: update
        properties:
            hibernate:
                dialect: org.hibernate.dialect.PostgreSQLDialect

server:
    port: 8080
