name: Deploy to Oracle Instance

on:
    push:
        branches:
            - main

jobs:
    deploy:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v3

            # Config 파일 저장소 복사
            - name: Clone Config Repository
              run: |
                  git clone https://${{ secrets.CONFIG_REPO_PAT }}@${{ secrets.CONFIG_REPO_URL }} config-repo
                  cp -r config-repo/travelingdog-prod.yml ./src/main/resources/application-build.yml

            - name: Setup SSH agent
              uses: webfactory/ssh-agent@v0.5.3
              with:
                  ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

            - name: Log in to Docker Hub
              uses: docker/login-action@v2
              with:
                  username: ${{ secrets.DOCKER_USERNAME }}
                  password: ${{ secrets.DOCKER_PASSWORD }}

            - name: Build Docker image
              run: |
                  docker build --no-cache -f Dockerfile.prod -t dmdmdm1322/travelingdog-backend:latest .

            - name: Push Docker image to Docker Hub
              run: |
                  docker push dmdmdm1322/travelingdog-backend:latest

            - name: Run docker compose on GCP instance
              run: |
                  ssh -o StrictHostKeyChecking=no dmdmdm1322@35.196.99.220 "
                    export POSTGRES_USER=${{ secrets.POSTGRES_USER }}
                    export POSTGRES_PASSWORD=${{ secrets.POSTGRES_PASSWORD }}
                    cd ~/traveling-dog-backend
                    git pull
                    docker compose -f docker-compose.prod.yml pull
                    docker compose -f docker-compose.prod.yml up --build -d
                  "
